-- Migration : sous-catégories + 7e catégorie « Kits » + REMPLACEMENT du catalogue
-- ATTENTION : supprime TOUS les produits existants puis insère le nouveau catalogue.
-- À exécuter dans Supabase > SQL Editor.
alter table products add column if not exists subcategory text default '';
alter table products add column if not exists image_url text;

delete from products;

insert into products (id, category, subcategory, title, description, price, stock) values
('dev-001','developpement','cartes-arduino-officielles-compatibles','Arduino UNO R3 CH340G','Cartes Arduino (Officielles & Compatibles)',0,0),
('dev-002','developpement','cartes-arduino-officielles-compatibles','Arduino UNO R3','Cartes Arduino (Officielles & Compatibles)',0,0),
('dev-003','developpement','cartes-arduino-officielles-compatibles','Arduino UNO R3 Original','Cartes Arduino (Officielles & Compatibles)',0,0),
('dev-004','developpement','cartes-arduino-officielles-compatibles','Arduino Nano','Cartes Arduino (Officielles & Compatibles)',0,0),
('dev-005','developpement','cartes-arduino-officielles-compatibles','Arduino Mega 2560','Cartes Arduino (Officielles & Compatibles)',0,0),
('dev-006','developpement','cartes-arduino-officielles-compatibles','Arduino Leonardo','Cartes Arduino (Officielles & Compatibles)',0,0),
('dev-007','developpement','cartes-arduino-officielles-compatibles','Arduino UNO R4 WiFi','Cartes Arduino (Officielles & Compatibles)',0,0),
('dev-008','developpement','cartes-arduino-officielles-compatibles','Arduino DUE','Cartes Arduino (Officielles & Compatibles)',0,0),
('dev-009','developpement','cartes-arduino-officielles-compatibles','Arduino Pro Mini','Cartes Arduino (Officielles & Compatibles)',0,0),
('dev-010','developpement','cartes-esp-iot-wifi-bluetooth','ESP32 WiFi + Bluetooth','Cartes ESP & IoT (WiFi / Bluetooth)',0,0),
('dev-011','developpement','cartes-esp-iot-wifi-bluetooth','ESP32-CAM','Cartes ESP & IoT (WiFi / Bluetooth)',0,0),
('dev-012','developpement','cartes-esp-iot-wifi-bluetooth','ESP32-C3 SuperMini','Cartes ESP & IoT (WiFi / Bluetooth)',0,0),
('dev-013','developpement','cartes-esp-iot-wifi-bluetooth','ESP8266 ESP-01','Cartes ESP & IoT (WiFi / Bluetooth)',0,0),
('dev-014','developpement','cartes-esp-iot-wifi-bluetooth','ESP8266 NodeMCU','Cartes ESP & IoT (WiFi / Bluetooth)',0,0),
('dev-015','developpement','autres-microcontroleurs-cartes-de-developpement','Raspberry Pi Pico / RP2040','Autres Microcontrôleurs & Cartes de Développement',0,0),
('dev-016','developpement','autres-microcontroleurs-cartes-de-developpement','STM32','Autres Microcontrôleurs & Cartes de Développement',0,0),
('dev-017','developpement','autres-microcontroleurs-cartes-de-developpement','ATtiny','Autres Microcontrôleurs & Cartes de Développement',0,0),
('aff-001','affichage','ecrans-lcd-oled','LCD 16×2 I2C','Écrans LCD & OLED',0,0),
('aff-002','affichage','ecrans-lcd-oled','LCD 16×2 sans I2C','Écrans LCD & OLED',0,0),
('aff-003','affichage','ecrans-lcd-oled','LCD 20×4','Écrans LCD & OLED',0,0),
('aff-004','affichage','ecrans-lcd-oled','OLED 0.96” I2C','Écrans LCD & OLED',0,0),
('aff-005','affichage','ecrans-lcd-oled','OLED 1.3”','Écrans LCD & OLED',0,0),
('aff-006','affichage','ecrans-tft-tactiles','TFT 1.8”','Écrans TFT & Tactiles',0,0),
('aff-007','affichage','ecrans-tft-tactiles','TFT 2.4”','Écrans TFT & Tactiles',0,0),
('aff-008','affichage','ecrans-tft-tactiles','TFT 3.5”','Écrans TFT & Tactiles',0,0),
('aff-009','affichage','matrices-afficheurs-7-segments','7-Segment 1 digit','Matrices & Afficheurs 7 Segments',0,0),
('aff-010','affichage','matrices-afficheurs-7-segments','7-Segment 4 digits','Matrices & Afficheurs 7 Segments',0,0),
('aff-011','affichage','matrices-afficheurs-7-segments','LED Matrix 8×8','Matrices & Afficheurs 7 Segments',0,0),
('aff-012','affichage','matrices-afficheurs-7-segments','LED Matrix MAX7219','Matrices & Afficheurs 7 Segments',0,0),
('aff-013','affichage','leds-eclairage','LED 5mm','LEDs & Éclairage',0,0),
('aff-014','affichage','leds-eclairage','RGB LED','LEDs & Éclairage',0,0),
('aff-015','affichage','leds-eclairage','WS2812B','LEDs & Éclairage',0,0),
('aff-016','affichage','leds-eclairage','RGB LED Strip','LEDs & Éclairage',0,0),
('aff-017','affichage','indicateurs-sonores-autres','Buzzer actif','Indicateurs Sonores & Autres',0,0),
('aff-018','affichage','indicateurs-sonores-autres','Buzzer passif','Indicateurs Sonores & Autres',0,0),
('aff-019','affichage','indicateurs-sonores-autres','IR LED / Indicator','Indicateurs Sonores & Autres',0,0),
('ali-001','alimentation','batteries-piles','Batterie 9V','Batteries & Piles',0,0),
('ali-002','alimentation','batteries-piles','Batterie 18650','Batteries & Piles',0,0),
('ali-003','alimentation','batteries-piles','Li-Po Battery','Batteries & Piles',0,0),
('ali-004','alimentation','supports-gestion-de-charge-bms','Connecteur 9V','Supports & Gestion de Charge (BMS)',0,0),
('ali-005','alimentation','supports-gestion-de-charge-bms','Battery Holder AA','Supports & Gestion de Charge (BMS)',0,0),
('ali-006','alimentation','supports-gestion-de-charge-bms','Battery Holder 18650','Supports & Gestion de Charge (BMS)',0,0),
('ali-007','alimentation','supports-gestion-de-charge-bms','TP4056 (Module de charge)','Supports & Gestion de Charge (BMS)',0,0),
('ali-008','alimentation','supports-gestion-de-charge-bms','BMS 1S','Supports & Gestion de Charge (BMS)',0,0),
('ali-009','alimentation','supports-gestion-de-charge-bms','BMS 2S/3S','Supports & Gestion de Charge (BMS)',0,0),
('ali-010','alimentation','convertisseurs-regulateurs-de-tension','LM2596 Buck Converter','Convertisseurs & Régulateurs de Tension',0,0),
('ali-011','alimentation','convertisseurs-regulateurs-de-tension','Boost Converter','Convertisseurs & Régulateurs de Tension',0,0),
('ali-012','alimentation','convertisseurs-regulateurs-de-tension','Buck/Boost Converter','Convertisseurs & Régulateurs de Tension',0,0),
('ali-013','alimentation','convertisseurs-regulateurs-de-tension','5V Voltage Regulator','Convertisseurs & Régulateurs de Tension',0,0),
('ali-014','alimentation','adaptateurs-alimentation-secteur','12V Adapter','Adaptateurs & Alimentation Secteur',0,0),
('ali-015','alimentation','adaptateurs-alimentation-secteur','5V USB Power Supply','Adaptateurs & Alimentation Secteur',0,0),
('ali-016','alimentation','adaptateurs-alimentation-secteur','DC Power Supply','Adaptateurs & Alimentation Secteur',0,0),
('comp-001','composants','composants-passifs-resistances-condensateurs','Résistances 1/4W','Composants Passifs (Résistances, Condensateurs...)',0,0),
('comp-002','composants','composants-passifs-resistances-condensateurs','Pack résistances','Composants Passifs (Résistances, Condensateurs...)',0,0),
('comp-003','composants','composants-passifs-resistances-condensateurs','Potentiomètre 10K','Composants Passifs (Résistances, Condensateurs...)',0,0),
('comp-004','composants','composants-passifs-resistances-condensateurs','Condensateur céramique','Composants Passifs (Résistances, Condensateurs...)',0,0),
('comp-005','composants','composants-passifs-resistances-condensateurs','Condensateur électrolytique','Composants Passifs (Résistances, Condensateurs...)',0,0),
('comp-006','composants','semi-conducteurs-diodes-transistors-ics','Diode 1N4007','Semi-conducteurs (Diodes, Transistors, ICs)',0,0),
('comp-007','composants','semi-conducteurs-diodes-transistors-ics','Diode 1N4148','Semi-conducteurs (Diodes, Transistors, ICs)',0,0),
('comp-008','composants','semi-conducteurs-diodes-transistors-ics','Zener Diode','Semi-conducteurs (Diodes, Transistors, ICs)',0,0),
('comp-009','composants','semi-conducteurs-diodes-transistors-ics','Transistor NPN','Semi-conducteurs (Diodes, Transistors, ICs)',0,0),
('comp-010','composants','semi-conducteurs-diodes-transistors-ics','Transistor PNP','Semi-conducteurs (Diodes, Transistors, ICs)',0,0),
('comp-011','composants','semi-conducteurs-diodes-transistors-ics','MOSFET','Semi-conducteurs (Diodes, Transistors, ICs)',0,0),
('comp-012','composants','semi-conducteurs-diodes-transistors-ics','555 Timer','Semi-conducteurs (Diodes, Transistors, ICs)',0,0),
('comp-013','composants','semi-conducteurs-diodes-transistors-ics','74HC595','Semi-conducteurs (Diodes, Transistors, ICs)',0,0),
('comp-014','composants','semi-conducteurs-diodes-transistors-ics','ULN2003','Semi-conducteurs (Diodes, Transistors, ICs)',0,0),
('comp-015','composants','semi-conducteurs-diodes-transistors-ics','L293D (Circuit Intégré)','Semi-conducteurs (Diodes, Transistors, ICs)',0,0),
('comp-016','composants','capteurs-d-environnement-temperature-humidite-gaz','DHT11 (Température/Humidité)','Capteurs d''Environnement (Température, Humidité, Gaz)',0,0),
('comp-017','composants','capteurs-d-environnement-temperature-humidite-gaz','DHT22 (Température/Humidité)','Capteurs d''Environnement (Température, Humidité, Gaz)',0,0),
('comp-018','composants','capteurs-d-environnement-temperature-humidite-gaz','DS18B20 (Température)','Capteurs d''Environnement (Température, Humidité, Gaz)',0,0),
('comp-019','composants','capteurs-d-environnement-temperature-humidite-gaz','Soil Moisture Sensor (Humidité du sol)','Capteurs d''Environnement (Température, Humidité, Gaz)',0,0),
('comp-020','composants','capteurs-d-environnement-temperature-humidite-gaz','Water Level Sensor (Niveau d''eau)','Capteurs d''Environnement (Température, Humidité, Gaz)',0,0),
('comp-021','composants','capteurs-d-environnement-temperature-humidite-gaz','Rain Sensor (Pluie)','Capteurs d''Environnement (Température, Humidité, Gaz)',0,0),
('comp-022','composants','capteurs-d-environnement-temperature-humidite-gaz','MQ-2 (Gaz combustible/Fumée)','Capteurs d''Environnement (Température, Humidité, Gaz)',0,0),
('comp-023','composants','capteurs-d-environnement-temperature-humidite-gaz','MQ-3 (Alcool)','Capteurs d''Environnement (Température, Humidité, Gaz)',0,0),
('comp-024','composants','capteurs-d-environnement-temperature-humidite-gaz','MQ-135 (Qualité de l''air)','Capteurs d''Environnement (Température, Humidité, Gaz)',0,0),
('comp-025','composants','capteurs-d-environnement-temperature-humidite-gaz','BMP280 (Pression/Température)','Capteurs d''Environnement (Température, Humidité, Gaz)',0,0),
('comp-026','composants','capteurs-d-environnement-temperature-humidite-gaz','BME280 (Pression/Température/Humidité)','Capteurs d''Environnement (Température, Humidité, Gaz)',0,0),
('comp-027','composants','capteurs-de-mouvement-distance-position','HC-SR04 (Ultrason / Distance)','Capteurs de Mouvement, Distance & Position',0,0),
('comp-028','composants','capteurs-de-mouvement-distance-position','HC-SR501 PIR (Mouvement)','Capteurs de Mouvement, Distance & Position',0,0),
('comp-029','composants','capteurs-de-mouvement-distance-position','IR Obstacle Sensor (Obstacle)','Capteurs de Mouvement, Distance & Position',0,0),
('comp-030','composants','capteurs-de-mouvement-distance-position','MPU6050 (Gyroscope/Accéléromètre)','Capteurs de Mouvement, Distance & Position',0,0),
('comp-031','composants','capteurs-de-mouvement-distance-position','Vibration Sensor','Capteurs de Mouvement, Distance & Position',0,0),
('comp-032','composants','capteurs-optiques-sonores-divers','LDR (Photorésistance / Lumière)','Capteurs Optiques, Sonores & Divers',0,0),
('comp-033','composants','capteurs-optiques-sonores-divers','Flame Sensor (Flamme)','Capteurs Optiques, Sonores & Divers',0,0),
('comp-034','composants','capteurs-optiques-sonores-divers','Hall Sensor (Magnétique)','Capteurs Optiques, Sonores & Divers',0,0),
('comp-035','composants','capteurs-optiques-sonores-divers','Sound Sensor (Son)','Capteurs Optiques, Sonores & Divers',0,0),
('comp-036','composants','capteurs-optiques-sonores-divers','Pulse Sensor (Rythme cardiaque)','Capteurs Optiques, Sonores & Divers',0,0),
('comp-037','composants','cablage-prototypage','Jumper Male-Male','Câblage & Prototypage',0,0),
('comp-038','composants','cablage-prototypage','Jumper Male-Female','Câblage & Prototypage',0,0),
('comp-039','composants','cablage-prototypage','Jumper Female-Female','Câblage & Prototypage',0,0),
('comp-040','composants','cablage-prototypage','Dupont wires','Câblage & Prototypage',0,0),
('comp-041','composants','cablage-prototypage','USB Cable Arduino','Câblage & Prototypage',0,0),
('comp-042','composants','cablage-prototypage','JST Connector','Câblage & Prototypage',0,0),
('comp-043','composants','cablage-prototypage','Pin Header','Câblage & Prototypage',0,0),
('comp-044','composants','cablage-prototypage','Terminal Block','Câblage & Prototypage',0,0),
('comp-045','composants','cablage-prototypage','Crocodile Clips','Câblage & Prototypage',0,0),
('comp-046','composants','cablage-prototypage','Breadboard 400 points','Câblage & Prototypage',0,0),
('comp-047','composants','cablage-prototypage','Breadboard 830 points','Câblage & Prototypage',0,0),
('comp-048','composants','cablage-prototypage','Prototype PCB','Câblage & Prototypage',0,0),
('out-001','outils','materiel-de-soudure','Fer à souder 60W','Matériel de Soudure',0,0),
('out-002','outils','materiel-de-soudure','Station de soudage','Matériel de Soudure',0,0),
('out-003','outils','materiel-de-soudure','Fil à souder','Matériel de Soudure',0,0),
('out-004','outils','materiel-de-soudure','Pompe à dessouder','Matériel de Soudure',0,0),
('out-005','outils','materiel-de-soudure','Tresse à dessouder','Matériel de Soudure',0,0),
('out-006','outils','materiel-de-soudure','Flux / pâte à souder','Matériel de Soudure',0,0),
('out-007','outils','appareils-de-mesure-diagnostic','Multimètre','Appareils de Mesure & Diagnostic',0,0),
('out-008','outils','appareils-de-mesure-diagnostic','Oscilloscope','Appareils de Mesure & Diagnostic',0,0),
('out-009','outils','appareils-de-mesure-diagnostic','Logic Analyzer','Appareils de Mesure & Diagnostic',0,0),
('out-010','outils','outillage-a-main-pinces-tournevis','Wire Stripper (Pince à dénuder)','Outillage à Main (Pinces, Tournevis...)',0,0),
('out-011','outils','outillage-a-main-pinces-tournevis','Pince coupante','Outillage à Main (Pinces, Tournevis...)',0,0),
('out-012','outils','outillage-a-main-pinces-tournevis','Pince à bec','Outillage à Main (Pinces, Tournevis...)',0,0),
('out-013','outils','outillage-a-main-pinces-tournevis','Crimping Tool (Pince à sertir)','Outillage à Main (Pinces, Tournevis...)',0,0),
('out-014','outils','outillage-a-main-pinces-tournevis','Tournevis précision','Outillage à Main (Pinces, Tournevis...)',0,0),
('out-015','outils','outillage-a-main-pinces-tournevis','Brucelles (Pinces de précision)','Outillage à Main (Pinces, Tournevis...)',0,0),
('out-016','outils','accessoires-d-atelier-rangement','Gaine thermorétractable','Accessoires d''Atelier & Rangement',0,0),
('out-017','outils','accessoires-d-atelier-rangement','Helping Hands (Troisième main)','Accessoires d''Atelier & Rangement',0,0),
('out-018','outils','accessoires-d-atelier-rangement','Boîte rangement composants','Accessoires d''Atelier & Rangement',0,0),
('rob-001','robotique','moteurs-cc-servomoteurs','DC Motor','Moteurs CC & Servomoteurs',0,0),
('rob-002','robotique','moteurs-cc-servomoteurs','Gear Motor (Moteur à engrenages)','Moteurs CC & Servomoteurs',0,0),
('rob-003','robotique','moteurs-cc-servomoteurs','Servo SG90','Moteurs CC & Servomoteurs',0,0),
('rob-004','robotique','moteurs-cc-servomoteurs','Servo MG996R','Moteurs CC & Servomoteurs',0,0),
('rob-005','robotique','moteurs-pas-a-pas-stepper','Stepper 28BYJ-48','Moteurs Pas à Pas (Stepper)',0,0),
('rob-006','robotique','moteurs-pas-a-pas-stepper','NEMA 17','Moteurs Pas à Pas (Stepper)',0,0),
('rob-007','robotique','controleurs-drivers-de-moteurs','L298N','Contrôleurs & Drivers de Moteurs',0,0),
('rob-008','robotique','controleurs-drivers-de-moteurs','L293D (Module/Shield)','Contrôleurs & Drivers de Moteurs',0,0),
('rob-009','robotique','controleurs-drivers-de-moteurs','A4988','Contrôleurs & Drivers de Moteurs',0,0),
('rob-010','robotique','controleurs-drivers-de-moteurs','DRV8825','Contrôleurs & Drivers de Moteurs',0,0),
('rob-011','robotique','controleurs-drivers-de-moteurs','ULN2003 Driver','Contrôleurs & Drivers de Moteurs',0,0),
('rob-012','robotique','controleurs-drivers-de-moteurs','Motor Shield','Contrôleurs & Drivers de Moteurs',0,0),
('rob-013','robotique','chassis-pieces-mecaniques','Roue robot','Châssis & Pièces Mécaniques',0,0),
('rob-014','robotique','chassis-pieces-mecaniques','Caster Wheel (Roue folle)','Châssis & Pièces Mécaniques',0,0),
('rob-015','robotique','chassis-pieces-mecaniques','Châssis Robot 2WD','Châssis & Pièces Mécaniques',0,0),
('rob-016','robotique','chassis-pieces-mecaniques','Châssis Robot 4WD','Châssis & Pièces Mécaniques',0,0),
('rob-017','robotique','chassis-pieces-mecaniques','Châssis Mecanum','Châssis & Pièces Mécaniques',0,0),
('rob-018','robotique','chassis-pieces-mecaniques','Robot Arm 6DOF','Châssis & Pièces Mécaniques',0,0),
('kit-001','kits','','Kit Arduino débutant','Kits complets pour démarrer',0,0),
('kit-002','kits','','Kit Arduino Starter','Kits complets pour démarrer',0,0),
('kit-003','kits','','Kit 37 capteurs','Kits complets pour démarrer',0,0),
('kit-004','kits','','Kit ESP32','Kits complets pour démarrer',0,0),
('kit-005','kits','','Kit Robot 2WD','Kits complets pour démarrer',0,0),
('kit-006','kits','','Kit Robot 4WD','Kits complets pour démarrer',0,0),
('kit-007','kits','','Kit RFID Arduino','Kits complets pour démarrer',0,0),
('kit-008','kits','','Kit bras robotique','Kits complets pour démarrer',0,0)
on conflict (id) do nothing;
