-- Seed catalogue RoboKit.ma — à exécuter une seule fois dans Supabase > SQL Editor
insert into products (id, category, title, description, price, stock) values
('dev-001', 'developpement', 'Arduino Uno R3', 'Carte de développement ATmega328P, 14 broches E/S numériques, idéale pour débuter.', 189, 24),
('dev-002', 'developpement', 'Raspberry Pi 4 Model B (4GB)', 'Mini-ordinateur ARM quad-core, Wi-Fi et Bluetooth intégrés, parfait pour vos projets IoT.', 749, 12),
('dev-003', 'developpement', 'ESP32 DevKit V1', 'Microcontrôleur double cœur avec Wi-Fi et Bluetooth, 30 broches, très polyvalent.', 95, 40),
('dev-004', 'developpement', 'Arduino Nano', 'Format compact, compatible breadboard, basé sur l''ATmega328.', 79, 35),
('dev-005', 'developpement', 'STM32 Blue Pill', 'Carte ARM Cortex-M3 à faible coût, 72 MHz, nombreux périphériques.', 45, 18),
('dev-006', 'developpement', 'Raspberry Pi Pico', 'Microcontrôleur RP2040 double cœur, parfait pour les projets embarqués légers.', 59, 50),
('dev-007', 'developpement', 'ESP8266 NodeMCU', 'Module Wi-Fi programmable, compatible IDE Arduino, faible consommation.', 65, 30),
('aff-001', 'affichage', 'Écran OLED 0.96" I2C', 'Écran monochrome 128x64, communication I2C, très lisible et peu énergivore.', 69, 28),
('aff-002', 'affichage', 'Écran LCD 16x2 avec module I2C', 'Afficheur alphanumérique rétroéclairé, idéal pour afficher données et menus.', 85, 22),
('aff-003', 'affichage', 'Module LED RGB WS2812B (bande 1m)', '60 LEDs adressables individuellement, parfait pour effets lumineux programmables.', 120, 15),
('aff-004', 'affichage', 'Afficheur 7 segments (paquet de 5)', 'Modules simples pour afficher chiffres, cathode commune.', 35, 40),
('aff-005', 'affichage', 'Écran TFT 2.4" tactile', 'Écran couleur haute résolution avec interface tactile résistive.', 159, 10),
('aff-006', 'affichage', 'LED 5mm assorties (lot de 100)', 'LEDs rouge, vert, bleu, jaune — parfaites pour prototypage et signalisation.', 29, 60),
('ali-001', 'alimentation', 'Batterie Li-Po 3.7V 1200mAh', 'Batterie rechargeable compacte avec connecteur JST, pour drones et robots.', 79, 20),
('ali-002', 'alimentation', 'Convertisseur DC-DC Buck LM2596', 'Module réducteur de tension réglable, courant jusqu''à 3A.', 25, 45),
('ali-003', 'alimentation', 'Power Bank 18650 (support 4 piles)', 'Boîtier avec module de charge, sortie USB 5V pour projets portables.', 39, 30),
('ali-004', 'alimentation', 'Alimentation 12V 2A avec adaptateur', 'Bloc secteur stabilisé, connecteur jack 5.5mm, idéal pour bancs d''essai.', 65, 18),
('ali-005', 'alimentation', 'Module régulateur AMS1117 (3.3V/5V)', 'Petit régulateur linéaire, très utilisé pour alimenter des modules sensibles.', 12, 70),
('ali-006', 'alimentation', 'Panneau solaire 6V 200mA', 'Mini panneau photovoltaïque pour projets autonomes et chargeurs solaires.', 55, 15),
('comp-001', 'composants', 'Kit résistances (600 pcs, 30 valeurs)', 'Assortiment complet de résistances 1/4W, boîte de rangement incluse.', 45, 35),
('comp-002', 'composants', 'Kit transistors NPN/PNP (100 pcs)', 'Assortiment de transistors courants (2N2222, BC547, TIP120...).', 55, 25),
('comp-003', 'composants', 'Câbles Dupont (M-M, M-F, F-F) 120 pcs', 'Jeu complet de câbles de liaison pour breadboard, longueur 20cm.', 35, 50),
('comp-004', 'composants', 'Kit capteurs 37-en-1', 'Ensemble de modules capteurs (température, gaz, tactile, infrarouge...).', 249, 14),
('comp-005', 'composants', 'Capteur ultrason HC-SR04', 'Mesure de distance par ultrasons, portée 2-400cm, très précis.', 22, 60),
('comp-006', 'composants', 'Breadboard 830 points', 'Plaque d''essai sans soudure, format standard pour prototypage rapide.', 29, 45),
('comp-007', 'composants', 'Kit condensateurs céramique/électrolytiques', '120 pièces, valeurs variées, essentiels pour tout circuit.', 38, 30),
('comp-008', 'composants', 'Connecteurs JST 2 broches (lot de 20)', 'Connecteurs mâle/femelle pour batteries et modules d''alimentation.', 18, 55),
('comp-009', 'composants', 'Boutons poussoirs tactiles (lot de 50)', 'Boutons 6x6mm 4 broches, parfaits pour interfaces utilisateur.', 20, 65),
('out-001', 'outils', 'Station de soudage réglable 60W', 'Fer à souder avec température ajustable, embouts interchangeables.', 189, 12),
('out-002', 'outils', 'Multimètre numérique', 'Mesure tension, courant, résistance et continuité — essentiel pour le diagnostic.', 99, 20),
('out-003', 'outils', 'Pince à dénuder et coupe-fil', 'Outil polyvalent pour préparer vos câbles électroniques.', 45, 30),
('out-004', 'outils', 'Boîtier de rangement composants (24 cases)', 'Organiseur transparent pour résistances, LEDs et petites pièces.', 59, 25),
('out-005', 'outils', 'Étain à souder 60/40 (100g)', 'Fil d''étain de qualité avec flux, diamètre 0.8mm.', 29, 40),
('out-006', 'outils', 'Troisième main avec loupe', 'Support avec pinces articulées et loupe intégrée pour soudure de précision.', 85, 16),
('rob-001', 'robotique', 'Kit châssis robot 2 roues motrices', 'Châssis acrylique avec moteurs DC, roues et support de pile — base idéale pour débuter.', 139, 18),
('rob-002', 'robotique', 'Servo moteur SG90 (9g)', 'Micro servomoteur léger, rotation 180°, très utilisé en robotique.', 25, 50),
('rob-003', 'robotique', 'Driver moteur L298N', 'Module double pont en H pour piloter 2 moteurs DC ou 1 moteur pas-à-pas.', 39, 35),
('rob-004', 'robotique', 'Moteur pas-à-pas NEMA17', 'Moteur haute précision, couple élevé, pour imprimantes 3D et CNC.', 110, 15),
('rob-005', 'robotique', 'Bras robotique kit DIY (6 DOF)', 'Kit complet avec servos, idéal pour apprentissage de la cinématique.', 459, 8),
('rob-006', 'robotique', 'Roues caoutchouc pour moteur DC (paire)', 'Roues compatibles avec moteurs DC standards, bon grip.', 22, 45),
('rob-007', 'robotique', 'Module bras de préhension (pince)', 'Pince robotique actionnée par servo, montage facile.', 75, 20)
on conflict (id) do nothing;
